<?php

namespace Database\Seeders;

use App\Models\Artist;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $vangogh = Artist::firstOrCreate([
            'name' => 'Vincent van Gogh'
        ]);

        $picasso = Artist::firstOrCreate([
            'name' => 'Pablo Picasso'
        ]);

        $raphael = Artist::firstOrCreate([
            'name' => 'Raphael'
        ]);

        $products = [
            // VAN GOGH
            [
                'title' => 'Bridges Across the Seine at Asnières',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1887,
                'price' => 450,
                'image' => 'images/art/van_gogh/Bridges_across_the_Seine_at_Asnieres.jpg',
                'description' => 'A calm riverside scene depicting bridges and reflections in the Seine.',
            ],
            [
                'title' => 'Café Terrace at Night',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1888,
                'price' => 950,
                'image' => 'images/art/van_gogh/Cafe_Terrace_at_Night.jpg',
                'description' => 'A vibrant night scene of a café illuminated under a starry sky.',
            ],
            [
                'title' => 'Fishing in the Spring',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1887,
                'price' => 500,
                'image' => 'images/art/van_gogh/Fishing_in_the_Spring.jpg',
                'description' => 'A peaceful spring landscape with figures fishing by the water.',
            ],
            [
                'title' => 'Fritillaries in a Copper Vase',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1887,
                'price' => 400,
                'image' => 'images/art/van_gogh/Fritillaries_in_a_Copper_Vase.jpg',
                'description' => 'A delicate still life of flowers in a reflective copper vase.',
            ],
            [
                'title' => 'Interior of a Restaurant',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1887,
                'price' => 420,
                'image' => 'images/art/van_gogh/Interior_of_a_Restaurant.jpg',
                'description' => 'Depicts a quiet restaurant interior with warm tones and perspective.',
            ],
            [
                'title' => 'Irises',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1889,
                'price' => 880,
                'image' => 'images/art/van_gogh/Irises.jpg',
                'description' => 'A vivid painting of blooming irises with bold colors and movement.',
            ],
            [
                'title' => 'Landscape with House and Ploughman',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1889,
                'price' => 600,
                'image' => 'images/art/van_gogh/Landscape_with_House_and_Ploughman.jpg',
                'description' => 'A rural landscape showing a farmer working the land.',
            ],
            [
                'title' => 'Red Vineyards at Arles',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1888,
                'price' => 700,
                'image' => 'images/art/van_gogh/Red_Vineyards_at_Arles.jpg',
                'description' => 'One of the few paintings sold during his lifetime, showing vineyard workers.',
            ],
            [
                'title' => 'Skull with Burning Cigarette',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1886,
                'price' => 350,
                'image' => 'images/art/van_gogh/Skull_with_burning_cigarette.jpg',
                'description' => 'A dark, humorous study of a skeleton smoking a cigarette.',
            ],
            [
                'title' => 'Still Life: Vase with Fifteen Sunflowers',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1888,
                'price' => 990,
                'image' => 'images/art/van_gogh/Still_Life_-_Vase_with_Fifteen_Sunflowers.jpg',
                'description' => 'One of the most iconic sunflower paintings with vibrant yellow tones.',
            ],
            [
                'title' => 'The Fourteenth of July Celebration in Paris',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1886,
                'price' => 480,
                'image' => 'images/art/van_gogh/The_fourteenth_of_july_celebration_in_Paris.jpg',
                'description' => 'A festive Parisian street decorated for Bastille Day.',
            ],
            [
                'title' => 'The Night Café',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1888,
                'price' => 870,
                'image' => 'images/art/van_gogh/The_Night_Cafe.jpg',
                'description' => 'A dramatic interior scene expressing tension through color and perspective.',
            ],
            [
                'title' => 'The Sower',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1888,
                'price' => 650,
                'image' => 'images/art/van_gogh/The_Sower.jpg',
                'description' => 'A symbolic depiction of a farmer sowing seeds at sunset.',
            ],
            [
                'title' => 'The Starry Night',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1889,
                'price' => 1000,
                'image' => 'images/art/van_gogh/The_Starry_Night.jpg',
                'description' => 'A swirling night sky over a quiet village, one of the most famous paintings ever.',
            ],
            [
                'title' => 'Vase with Red Poppies',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1886,
                'price' => 430,
                'image' => 'images/art/van_gogh/Vase_with_Red_Poppies.jpg',
                'description' => 'A simple yet expressive still life of red poppies in a vase.',
            ],
            [
                'title' => 'View from Vincent’s Room in the Rue Lepic',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1887,
                'price' => 520,
                'image' => 'images/art/van_gogh/View_from_Vincents_room_in_the_Rue_Lepic.jpg',
                'description' => 'A view of Paris rooftops from Van Gogh’s apartment window.',
            ],
            [
                'title' => 'Wheat Field with Cypresses',
                'artist_id' => $vangogh->artist_id,
                'genre' => 'Impressionism',
                'year' => 1889,
                'price' => 920,
                'image' => 'images/art/van_gogh/Wheat_Field_with_Cypresses_at_the_Haude_Galline_near_Eygalieres.jpg',
                'description' => 'A dynamic landscape with cypress trees and a vivid sky.',
            ],

            // RAPHAEL
            [
                'title' => 'Adam and Eve (Stanza della Segnatura)',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1511,
                'price' => 700,
                'image' => 'images/art/raphael/adam-and-eve-from-the-stanza-della-segnatura-detail-1511.jpg',
                'description' => 'A fresco detail depicting Adam and Eve with classical balance and harmony.',
            ],
            [
                'title' => 'Bridgewater Madonna',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1511,
                'price' => 850,
                'image' => 'images/art/raphael/bridgewater-madonna-1511.jpg',
                'description' => 'A serene depiction of the Madonna and Child with soft composition.',
            ],
            [
                'title' => 'Christ Blessing',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => null,
                'price' => 600,
                'image' => 'images/art/raphael/christ-blessing.jpg',
                'description' => 'A devotional image of Christ offering a blessing gesture.',
            ],
            [
                'title' => 'Madonna of the Goldfinch',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1506,
                'price' => 950,
                'image' => 'images/art/raphael/madonna-of-the-goldfinch.jpg',
                'description' => 'A famous composition of Mary, Jesus, and John the Baptist with a goldfinch.',
            ],
            [
                'title' => 'Portrait of a Lady with a Unicorn',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1506,
                'price' => 780,
                'image' => 'images/art/raphael/portrait-of-a-lady-with-a-unicorn-1506.jpg',
                'description' => 'A refined portrait symbolizing purity with a unicorn.',
            ],
            [
                'title' => 'Portrait of Pietro Bembo',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1504,
                'price' => 650,
                'image' => 'images/art/raphael/portrait-of-the-young-pietro-bembo-1504.jpg',
                'description' => 'A portrait of the young scholar Pietro Bembo.',
            ],
            [
                'title' => 'Self Portrait',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1506,
                'price' => 720,
                'image' => 'images/art/raphael/self-portrait-1.jpg',
                'description' => 'A self-portrait showing the artist’s refined style and calm expression.',
            ],
            [
                'title' => 'Saint George and the Dragon',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1505,
                'price' => 880,
                'image' => 'images/art/raphael/st-george-and-the-dragon.jpg',
                'description' => 'A dynamic scene of Saint George slaying the dragon.',
            ],
            [
                'title' => 'Saint Michael (1505)',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1505,
                'price' => 870,
                'image' => 'images/art/raphael/st-michael-1505.jpg',
                'description' => 'An early depiction of Saint Michael defeating evil.',
            ],
            [
                'title' => 'Saint Michael Overwhelming the Demon',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1518,
                'price' => 900,
                'image' => 'images/art/raphael/st-michael-overwhelming-the-demon-1518.jpg',
                'description' => 'A dramatic composition of Saint Michael defeating a demon.',
            ],
            [
                'title' => 'The Battle of Ostia',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1514,
                'price' => 830,
                'image' => 'images/art/raphael/the-battle-of-ostia-1514.jpg',
                'description' => 'A historical fresco depicting a naval victory.',
            ],
            [
                'title' => 'The Madonna of Foligno',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1512,
                'price' => 920,
                'image' => 'images/art/raphael/the-madonna-of-foligno-1512.jpg',
                'description' => 'A grand altarpiece with the Madonna in a heavenly setting.',
            ],
            [
                'title' => 'The Sistine Madonna',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1513,
                'price' => 1000,
                'image' => 'images/art/raphael/the-sistine-madonna-1513.jpg',
                'description' => 'One of Raphael’s most famous works featuring the iconic cherubs.',
            ],
            [
                'title' => 'The Transfiguration',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1520,
                'price' => 980,
                'image' => 'images/art/raphael/the-transfiguration-1520.jpg',
                'description' => 'Raphael’s final masterpiece combining two biblical scenes.',
            ],
            [
                'title' => 'La Donna Velata (The Veiled Woman)',
                'artist_id' => $raphael->artist_id,
                'genre' => 'Renaissance',
                'year' => 1516,
                'price' => 860,
                'image' => 'images/art/raphael/the-veiled-woman-or-la-donna-velata.jpg',
                'description' => 'A soft and intimate portrait of a woman with a veil.',
            ],

            // PICASSO
            [
                'title' => 'Acrobat',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1930,
                'price' => 700,
                'image' => 'images/art/picasso/acrobat-1930.jpg',
                'description' => 'A stylized depiction of an acrobat showing dynamic movement and abstraction.',
            ],
            [
                'title' => 'Ascet',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1903,
                'price' => 500,
                'image' => 'images/art/picasso/ascet-1903.jpg',
                'description' => 'A melancholic figure reflecting Picasso’s Blue Period themes.',
            ],
            [
                'title' => 'Crying Woman',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1937,
                'price' => 950,
                'image' => 'images/art/picasso/crying-woman-1937-1.jpg',
                'description' => 'An emotional portrait symbolizing pain and suffering during wartime.',
            ],
            [
                'title' => 'Fruit Dish',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1917,
                'price' => 600,
                'image' => 'images/art/picasso/fruit-dish-1917.jpg',
                'description' => 'A still life composition with geometric abstraction.',
            ],
            [
                'title' => 'Interior with Easel',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1926,
                'price' => 650,
                'image' => 'images/art/picasso/interior-with-easel-1926.jpg',
                'description' => 'An abstract interior scene featuring an easel.',
            ],
            [
                'title' => 'Madonna with Garland',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1904,
                'price' => 550,
                'image' => 'images/art/picasso/madonna-with-garland-1904.jpg',
                'description' => 'A softer and warmer composition from Picasso’s Rose Period.',
            ],
            [
                'title' => 'Manola',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => null,
                'price' => 520,
                'image' => 'images/art/picasso/manola.jpg',
                'description' => 'A portrait reflecting early stylistic development.',
            ],
            [
                'title' => 'Portrait of Marie-Thérèse Walter with Garland',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1937,
                'price' => 900,
                'image' => 'images/art/picasso/portrait-of-marie-thérèse-walter-with-garland-1937.jpg',
                'description' => 'A colorful and abstract portrait of Picasso’s muse.',
            ],
            [
                'title' => 'The Absinthe Drinker',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1901,
                'price' => 800,
                'image' => 'images/art/picasso/the-absinthe-drinker-1901.jpg',
                'description' => 'A somber depiction of isolation and urban life.',
            ],
            [
                'title' => 'Untitled',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1936,
                'price' => 400,
                'image' => 'images/art/picasso/untitled-1936.jpg',
                'description' => 'An abstract composition with expressive forms.',
            ],
            [
                'title' => 'Violin',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => null,
                'price' => 620,
                'image' => 'images/art/picasso/violin.jpg',
                'description' => 'A fragmented depiction of a violin using geometric shapes.',
            ],
            [
                'title' => 'Woman’s Head',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1934,
                'price' => 750,
                'image' => 'images/art/picasso/woman-s-head-1934.jpg',
                'description' => 'An abstract portrait emphasizing distorted facial features.',
            ],
            [
                'title' => 'Woman with a Shirt Sitting in a Chair',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1913,
                'price' => 680,
                'image' => 'images/art/picasso/woman-with-a-shirt-sitting-in-a-chair-1913.jpg',
                'description' => 'A seated figure represented in early Cubist style.',
            ],
            [
                'title' => 'Woman with Guitar and Piano',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1911,
                'price' => 720,
                'image' => 'images/art/picasso/woman-with-guitar-and-piano-1911.jpg',
                'description' => 'A complex Cubist composition combining musical elements.',
            ],
            [
                'title' => 'Woman with Hat',
                'artist_id' => $picasso->artist_id,
                'genre' => 'Cubism',
                'year' => 1962,
                'price' => 770,
                'image' => 'images/art/picasso/woman-with-hat-1962-1.jpg',
                'description' => 'A later work featuring bold colors and expressive lines.',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        // TOOLS
        $tools = [
            [
                'title' => 'Professional Brushes Set',
                'artist_id' => null,
                'genre' => 'Brushes',
                'category' => 'tool',
                'year' => 2026,
                'price' => 45,
                'image' => 'images/art/tools/brushes.jpg',
                'description' => 'Set of 12 professional artist brushes for oil and acrylic painting.',
            ],
            [
                'title' => 'Acrylic Paint Set',
                'artist_id' => null,
                'genre' => 'Paint',
                'category' => 'tool',
                'year' => 2026,
                'price' => 60,
                'image' => 'images/art/tools/acrylic_paint.jpg',
                'description' => '24 colors of high-quality acrylic paint in 20ml tubes.',
            ],
            [
                'title' => 'Oil Paint Set',
                'artist_id' => null,
                'genre' => 'Paint',
                'category' => 'tool',
                'year' => 2026,
                'price' => 75,
                'image' => 'images/art/tools/oil_paint.jpg',
                'description' => '18 colors of professional oil paint for canvas work.',
            ],
            [
                'title' => 'Watercolor Paint Set',
                'artist_id' => null,
                'genre' => 'Paint',
                'category' => 'tool',
                'year' => 2026,
                'price' => 35,
                'image' => 'images/art/tools/watercolor_paint.jpg',
                'description' => 'Compact watercolor set with 36 vibrant colors.',
            ],
            [
                'title' => 'Wooden Easel',
                'artist_id' => null,
                'genre' => 'Easels',
                'category' => 'tool',
                'year' => 2026,
                'price' => 120,
                'image' => 'images/art/tools/easel.jpg',
                'description' => 'Adjustable wooden studio easel, holds canvases up to 120cm.',
            ],
            [
                'title' => 'Stretched Canvas',
                'artist_id' => null,
                'genre' => 'Canvas',
                'category' => 'tool',
                'year' => 2026,
                'price' => 25,
                'image' => 'images/art/tools/canvas.jpg',
                'description' => 'Pre-stretched cotton canvas 50×60cm, ready to paint.',
            ],
            [
                'title' => 'Wooden Palette',
                'artist_id' => null,
                'genre' => 'Accessories',
                'category' => 'tool',
                'year' => 2026,
                'price' => 18,
                'image' => 'images/art/tools/palette.jpg',
                'description' => 'Classic oval wooden palette for mixing oil and acrylic paints.',
            ],
            [
                'title' => 'Palette Knife Set',
                'artist_id' => null,
                'genre' => 'Accessories',
                'category' => 'tool',
                'year' => 2026,
                'price' => 22,
                'image' => 'images/art/tools/palette_knife.jpg',
                'description' => 'Set of 5 stainless steel palette knives for texture and mixing.',
            ],
            [
                'title' => 'Brush Cleaner Jar',
                'artist_id' => null,
                'genre' => 'Accessories',
                'category' => 'tool',
                'year' => 2026,
                'price' => 12,
                'image' => 'images/art/tools/water_jar.jpg',
                'description' => 'Glass jar with metal coil for cleaning brushes.',
            ],
            [
                'title' => 'Paint Thinner',
                'artist_id' => null,
                'genre' => 'Accessories',
                'category' => 'tool',
                'year' => 2026,
                'price' => 15,
                'image' => 'images/art/tools/thinner.jpg',
                'description' => 'Odourless paint thinner for oil paints, 500ml.',
            ],
        ];

        foreach ($tools as $tool) {
            Product::create($tool);
        }
    }
}
